[build]
  # Run typecheck & lint before building. If these fail, the build stops (strict).
  command = "npm run typecheck && npm run lint && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
