[build]
  command = "npm install --include=dev --no-fund --no-audit --no-optional && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  CI = "true"
  NPM_CONFIG_LOGLEVEL = "verbose"
  NPM_CONFIG_OPTIONAL = "false"
  NPM_CONFIG_PRODUCTION = "false" # <-- critical: don't drop devDependencies

[[plugins]]
  package = "@netlify/plugin-nextjs"
